services:
  - type: web
    name: wedding-wizard
    env: node
    nodeVersion: 18
    buildCommand: npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: HTTPS
        value: "true" 