services:
  - type: web
    name: wedding-wizard
    env: node
    nodeVersion: 18
    buildCommand: npm install --include=dev && npm run build:client && mkdir -p dist && cp scripts/minimal-server.js dist/index.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: HTTPS
        value: "true" 